# Generated by Django 5.2.10 on 2026-03-26 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_hash_teacher_passwords'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='teachers/'),
        ),
    ]
