# Generated by Django 5.2.10 on 2026-03-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="students/"),
        ),
    ]
