# Generated by Django 5.2.10 on 2026-04-25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0005_feeinvoice_feepayment"),
        ("accounts", "0002_hash_teacher_passwords"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeePlan",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=150)),
                ("monthly_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("due_day", models.PositiveSmallIntegerField(default=10)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "class_section",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="fee_plans", to="academics.classsection"),
                ),
            ],
            options={
                "ordering": ("class_section", "title"),
                "unique_together": {("class_section", "title")},
            },
        ),
        migrations.AddField(
            model_name="feeinvoice",
            name="billing_month",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="feeinvoice",
            name="source_plan",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="generated_invoices", to="academics.feeplan"),
        ),
        migrations.CreateModel(
            name="FeeNotification",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("notification_type", models.CharField(choices=[("DUE_SOON", "Due Soon"), ("OVERDUE", "Overdue")], max_length=12)),
                ("title", models.CharField(max_length=200)),
                ("body", models.TextField()),
                ("notified_for_date", models.DateField()),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "invoice",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="notifications", to="academics.feeinvoice"),
                ),
                (
                    "parent",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="fee_notifications", to="accounts.parentprofile"),
                ),
                (
                    "student",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="fee_notifications", to="academics.student"),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "unique_together": {("parent", "invoice", "notification_type", "notified_for_date")},
            },
        ),
    ]
