# Generated by Django 5.2.10 on 2026-03-03 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0003_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
