# Generated by Django 5.2.10 on 2026-03-25 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_student_photo'),
        ('accounts', '0002_hash_teacher_passwords'),
        ('communication', '0007_conversationgroup'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='conversationthread',
            name='uniq_parent_student_teacher_thread',
        ),
        migrations.AlterUniqueTogether(
            name='conversationthread',
            unique_together={('student', 'parent', 'teacher')},
        ),
    ]
